all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /root/.ssh/vm-management
    ansible_python_interpreter: /usr/bin/python3
    lan_subnet: 192.168.37.0/24
    common_dir: "{{ inventory_dir }}/common"

  hosts:
    vm_host:
      ansible_host: localhost
      ansible_connection: local

    nas:
      ansible_host: nas.home.arpa
      ip_address: 192.168.37.10

    tailscale:
      ansible_host: tailscale.home.arpa
      system_hostname: tailscale
      proxmox_ctid: 1021

    print_server:
      ansible_host: print-server.home.arpa
      system_hostname: print-server
      proxmox_ctid: 1041

    paperless:
      ansible_host: paperless-temp.home.arpa
      system_hostname: paperless-temp
      proxmox_vmid: 1099
